springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  packages-to-scan: com.longan.user.controller,com.longan.goods.controller,com.longan.order.controller,com.longan.chat.controller,com.longan.common.controller

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/longan_apex?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB  # 限制单张图片大小
      max-request-size: 30MB


mybatis-plus:
  mapper-locations: classpath*:*/mapper/*.xml

  type-aliases-package: com.longan.user.entity,com.longan.goods.entity,com.longan.order.entity,com.longan.chat.entity,com.longan.common.entity

  configuration:
    # 下划线转驼峰
    map-underscore-to-camel-case: true
    # 打印 SQL
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  global-config:
    db-config:
      id-type: auto
      insert-strategy: not_null

server:
  error:
    include-message: always
    include-stacktrace: always
longan:
  upload:
    # 容器内部访问的路径
    path: /var/www/pic_bed
    # Nginx 暴露出来的访问域名
    domain: http://localhost:8888/